/**
 * Created by caohongming on 2016/10/24.
 */
var allOptions = new Map(); //存放"全部" 订单链接下的 所有需要展示的Options
var allUrlMap = new Map(); //存放"全部" 订单链接下的 所有需要展示的获取数据url
var transMap = new Map(); //存放左侧菜单 Key:type, Value: desc 供翻译使用
var parameter = new Map();// 存放按天查询 所有的查询条件
var queryWeekMap = new Map(); // 存放按周查询的查询条件
var queryMonthMap = new Map(); // 存放按月查询的查询条件
var dayMap = new Map(); // 存放按天查询, 动态增加过那些天
var chart;
var options;
var options2;// 按月, 按周
var oneTooltipWM = "<span style=\"color:{series.color}\">{point.name}</span>: <b>{point.y}</b><br/>"; // 按周按月的格式化方式
var tooltipTitle = ''; //按周按月的提示标题
var lastMinutes = '';
var time = 0;
var tableName = '';

transMap.put('order-99', '全部订单(新)');
transMap.put('order-20', 'pc端订单');
transMap.put('order-0', '全部订单');
transMap.put('order-100', '一般订单');
transMap.put('order-10', '手机订单');
transMap.put('order-23', '手Q订单');
transMap.put('order-19', '微信订单');
transMap.put('order-3', '余额订单');
transMap.put('order-2', '优惠券订单');
transMap.put('order-4', '礼品卡订单');
transMap.put('order-12', '京豆优惠购');
transMap.put('order-26', '免运费券订单');
transMap.put('order-11', '京豆订单');
transMap.put('order-121', 'PopFbp');
transMap.put('order-122', 'PopSop');
transMap.put('order-123', 'PopLbp');
transMap.put('order-125', 'POP SOPL');
transMap.put('order-128', '团购(虚拟)');
transMap.put('order-137', '话费充值');
transMap.put('order-134', '游戏点卡');
transMap.put('order-136', '彩票');
transMap.put('order-22', '网购浏览器订单');
transMap.put('order-18', '易迅订单');
transMap.put('order-6', '新用户订单');
transMap.put('order-9', '子单监控');
transMap.put('order-17', '团购(实物)');
transMap.put('order-102', '夺宝岛订单');
transMap.put('order-13', '预售订单');
transMap.put('order-118', '厂商直送');
transMap.put('order-14', '轻松购订单');
transMap.put('order-15', '礼品购订单');
transMap.put('order-133', '电子礼品卡');
transMap.put('order-135', '机票');
transMap.put('order-138', '电子书订单');
transMap.put('order-142', '通用合约计划');
transMap.put('order-144', '景点门票');
transMap.put('order-147', '旅游');
transMap.put('order-149', '实物礼品卡');
transMap.put('order-151', '误购取件费订单');
transMap.put('order-153', '票务订单');
transMap.put('order-154', '线下礼品卡订单');
transMap.put('order-158', '数字音乐');
transMap.put('order-161', 'EPT订单');
transMap.put('order-162', '网页游戏');
transMap.put('payment-10000', '支付总数');
transMap.put('payment-10107', '北京快钱(企业网银)');
transMap.put('payment-10119', '招行分期');
transMap.put('payment-10501', '光大分期');
transMap.put('payment-10127', '民生分期');
transMap.put('payment-10301', '建行银行');
transMap.put('payment-10302', '邮政储蓄(借)');
transMap.put('payment-10305', '中国银行实物');
transMap.put('payment-10307', '招商银行(实物)');
transMap.put('payment-10313', '邮政储蓄(信)');
transMap.put('payment-10320', '中国银行(虚拟)');
transMap.put('payment-10163', '成都银联客户端');
transMap.put('payment-10169', '邮局汇款');
transMap.put('payment-10165', '银联WAP实物');
transMap.put('payment-10167', '银联电子书');
transMap.put('payment-10172', 'Paypal EPT');
transMap.put('payment-10162', '快钱资金归集');
transMap.put('payment-10139', '快捷快钱虚拟');
transMap.put('payment-10138', '快捷快钱实物');
transMap.put('payment-10122', '快钱实物');
transMap.put('payment-10124', '移动支付');
transMap.put('payment-10136', '移动虚拟');
transMap.put('payment-10137', '快钱虚拟');
transMap.put('payment-10603', '银联实物');
transMap.put('payment-10143', '易宝借记卡');
transMap.put('payment-10144', '易宝余额充值');
transMap.put('payment-10145', '拉卡拉实物');
transMap.put('club-20001', '商品评价');
transMap.put('club-20002', '咨询');
transMap.put('club-20003', '晒单');
transMap.put('login-ip-0', '北京');
transMap.put('login-ip-1', '上海');
transMap.put('login-ip-2', '天津');
transMap.put('login-ip-3', '重庆');
transMap.put('login-ip-4', '河北');
transMap.put('login-ip-5', '山西');
transMap.put('login-ip-6', '河南');
transMap.put('login-ip-7', '辽宁');
transMap.put('login-ip-8', '吉林');
transMap.put('login-ip-9', '黑龙江');
transMap.put('login-ip-10', '内蒙古');
transMap.put('login-ip-11', '江苏');
transMap.put('login-ip-12', '山东');
transMap.put('login-ip-13', '安徽');
transMap.put('login-ip-14', '浙江');
transMap.put('login-ip-15', '福建');
transMap.put('login-ip-16', '湖北');
transMap.put('login-ip-17', '湖南');
transMap.put('login-ip-18', '广东');
transMap.put('login-ip-19', '广西');
transMap.put('login-ip-20', '江西');
transMap.put('login-ip-21', '四川');
transMap.put('login-ip-22', '海南');
transMap.put('login-ip-23', '贵州');
transMap.put('login-ip-24', '云南');
transMap.put('login-ip-25', '西藏');
transMap.put('login-ip-26', '陕西');
transMap.put('login-ip-27', '甘肃');
transMap.put('login-ip-28', '青海');
transMap.put('login-ip-29', '宁夏');
transMap.put('login-ip-30', '新疆');
transMap.put('login-ip-31', '台湾');
transMap.put('login-ip-32', '香港');
transMap.put('login-ip-33', '澳门');
transMap.put('register-ip-0', '北京');
transMap.put('register-ip-1', '上海');
transMap.put('register-ip-2', '天津');
transMap.put('register-ip-3', '重庆');
transMap.put('orderpipesubmitip-0', '北京');
transMap.put('orderpipesubmitip-1', '上海');
transMap.put('register-ip-4', '河北');
transMap.put('register-ip-5', '山西');
transMap.put('orderpipesubmitip-2', '天津');
transMap.put('orderpipesubmitip-3', '重庆');
transMap.put('register-ip-6', '河南');
transMap.put('register-ip-7', '辽宁');
transMap.put('orderpipesubmitip-4', '河北');
transMap.put('orderpipesubmitip-5', '山西');
transMap.put('register-ip-8', '吉林');
transMap.put('register-ip-9', '黑龙江');
transMap.put('orderpipesubmitip-6', '河南');
transMap.put('orderpipesubmitip-7', '辽宁');
transMap.put('register-ip-10', '内蒙古');
transMap.put('register-ip-11', '江苏');
transMap.put('orderpipesubmitip-8', '吉林');
transMap.put('orderpipesubmitip-9', '黑龙江');
transMap.put('register-ip-12', '山东');
transMap.put('order-143', '电影票');
transMap.put('order-119', '客服补件');
transMap.put('register-ip-13', '安徽');
transMap.put('orderpipesubmitip-10', '内蒙古');
transMap.put('orderpipesubmitip-11', '江苏');
transMap.put('register-ip-14', '浙江');
transMap.put('order-108', '服务产品');
transMap.put('register-ip-15', '福建');
transMap.put('orderpipesubmitip-12', '山东');
transMap.put('orderpipesubmitip-13', '安徽');
transMap.put('register-ip-16', '湖北');
transMap.put('order-8', '修改订单');
transMap.put('register-ip-17', '湖南');
transMap.put('orderpipesubmitip-14', '浙江');
transMap.put('orderpipesubmitip-15', '福建');
transMap.put('register-ip-18', '广东');
transMap.put('order-116', '直接赔偿');
transMap.put('register-ip-19', '广西');
transMap.put('orderpipesubmitip-16', '湖北');
transMap.put('orderpipesubmitip-17', '湖南');
transMap.put('register-ip-20', '江西');
transMap.put('order-111', '售后调货');
transMap.put('register-ip-21', '四川');
transMap.put('orderpipesubmitip-18', '广东');
transMap.put('orderpipesubmitip-19', '广西');
transMap.put('register-ip-22', '海南');
transMap.put('register-ip-23', '贵州');
transMap.put('orderpipesubmitip-20', '江西');
transMap.put('orderpipesubmitip-21', '四川');
transMap.put('register-ip-24', '云南');
transMap.put('register-ip-25', '西藏');
transMap.put('orderpipesubmitip-22', '海南');
transMap.put('orderpipesubmitip-23', '贵州');
transMap.put('register-ip-26', '陕西');
transMap.put('register-ip-27', '甘肃');
transMap.put('orderpipesubmitip-24', '云南');
transMap.put('orderpipesubmitip-32', '香港');
transMap.put('register-ip-28', '青海');
transMap.put('register-ip-29', '宁夏');
transMap.put('register-ip-30', '新疆');
transMap.put('register-ip-31', '台湾');
transMap.put('register-ip-32', '香港');
transMap.put('register-ip-33', '澳门');
transMap.put('payment-10152', '银联快捷(实物)');
transMap.put('payment-10153', '银联快捷(虚拟)');
transMap.put('order-type--1', '订单监控');
transMap.put('orderpipeoverstock--1', '管道消息积压');
transMap.put('orderpipeerror--1', '管道消息错误');
transMap.put('payment--1', '支付监控');
transMap.put('club--1', '社区监控');
transMap.put('login--1', '登陆量监控');
transMap.put('login-ip--1', '登陆区域监控');
transMap.put('register--1', '注册量监控');
transMap.put('register-ip--1', '注册区域监控');
transMap.put('club-20007', '商品评价回复');
transMap.put('club-20008', '晒单回复');
transMap.put('club-20004', '讨论帖');
transMap.put('club-20011', '讨论帖回复');
transMap.put('club-20006', '圈子帖');
transMap.put('club-20012', '圈子帖回复');
transMap.put('club-20005', '问答帖');
transMap.put('club-20009', '问答帖回复');
transMap.put('balance--1', '余额监控');
transMap.put('balance-70800', '余额充值');
transMap.put('payment-10147', '网银在线实物');
transMap.put('payment-10148', '网银在线虚拟');
transMap.put('coupon--1', '优惠券监控');
transMap.put('coupon-130000', '优惠券发放');
transMap.put('coupon-140000', '未发放优惠券任务数');
transMap.put('login-0', '全部登陆量');
transMap.put('login-10001', '主站全部登陆量');
transMap.put('login-10002', 'SOA全部登陆量');
transMap.put('login-11', 'pin成功');
transMap.put('login-110', 'pin成功-主站');
transMap.put('login-12', '邮箱成功');
transMap.put('login-120', '邮箱成功-主站');
transMap.put('login-13', '手机成功');
transMap.put('login-130', '手机成功-主站');
transMap.put('login-21', '密码错误');
transMap.put('login-210', '密码错误-主站');
transMap.put('login-22', '无效用户');
transMap.put('register-0', '全部注册量');
transMap.put('login-220', '无效用户-主站');
transMap.put('register-10002', 'SOA全部注册量');
transMap.put('login-23', '用户不存在');
transMap.put('register-10001', '主站全部注册量');
transMap.put('login-230', '用户不存在-主站');
transMap.put('register-20002', 'App注册');
transMap.put('register-20003', 'PC端联合登陆注册');
transMap.put('register-20004', 'APP端联合登陆注册');
transMap.put('register-20007', '易迅注册');
transMap.put('register-20008', '总代注册');
transMap.put('register-20009', '拍拍注册');
transMap.put('register-11', '个人pin注册');
transMap.put('register-12', '个人邮箱注册');
transMap.put('register-20005', '手Q注册');
transMap.put('register-20006', '微店注册');
transMap.put('register-13', '个人手机注册');
transMap.put('login-24', '登陆被锁');
transMap.put('login-25', '黑名单用户');
transMap.put('register-21', '企业pin注册');
transMap.put('register-22', '企业邮箱注册');
transMap.put('login-26', '基础登陆信息无效');
transMap.put('login-27', '其他原因');
transMap.put('register-23', '企业手机注册');
transMap.put('productsort--1', '商品分类统计');
transMap.put('productsort-0', '商品分类统计');
transMap.put('order-164', '非车险保险订单');
transMap.put('order-165', '车险订单');
transMap.put('order-139', '酒店订单');
transMap.put('orderpipeerror-0', '管道消息错误');
transMap.put('orderpipeoverstock-0', '管道消息积压');
transMap.put('gms--1', '商品方法调用监控');
transMap.put('gms-150001', 'POP商品保存');
transMap.put('gms-150002', 'POP修改商品信息infos');
transMap.put('gms-150003', 'POP修改商品信息');
transMap.put('gms-150004', 'POP批量保存商品属性');
transMap.put('gms-150005', 'POP批量保存SKU税率');
transMap.put('gms-150006', 'POP修改SKU长图');
transMap.put('gms-150007', 'POP批量SKU上下柜');
transMap.put('gms-150008', 'POP批量保存区域限制');
transMap.put('gms-150009', 'POP类型删除区域限制');
transMap.put('gms-150010', 'POP批量添加图片信息');
transMap.put('order-16', '闪购订单');
transMap.put('order-183', '国际机票');
transMap.put('order-21', '京东E卡');
transMap.put('order-24', '虚拟组套');
transMap.put('taskorderoverstock--1', '订单任务');
transMap.put('taskorderoverstock-0', '全部任务');
transMap.put('taskorderoverstock-1224', '订单老下传');
transMap.put('taskorderoverstock-1154', '对账消息');
transMap.put('taskorderoverstock-1159', '先款推送OFW');
transMap.put('taskorderoverstock-111100', '订单完成消息');
transMap.put('taskorderoverstock-1102100', '订单取消消息');
transMap.put('ordercomplete-0', '完成订单');
transMap.put('ordercancel-0', '取消订单');
transMap.put('ordercomplete-1', '虚拟完成');
transMap.put('order-25', '通用下单');
transMap.put('order-33', '手机优惠券');
transMap.put('riskMonitor--1', '虚拟业务监控');
transMap.put('riskMonitor-51001', '手机充值移动端订单量');
transMap.put('order-34', 'pc优惠券');
transMap.put('order-35', '微信优惠券');
transMap.put('riskMonitor-51002', '手机充值PC端订单量');
transMap.put('riskMonitor-51003', '手机充值企销订单量');
transMap.put('order-36', '手Q优惠券');
transMap.put('riskMonitor-51004', '手机充值移动端支付量');
transMap.put('riskMonitor-51005', '手机充值PC端支付量');
transMap.put('riskMonitor-51006', '手机充值企销支付量');
transMap.put('order-27', '秒杀订单');
transMap.put('riskMonitor-52004', '彩票IOS支付量');
transMap.put('riskMonitor-52005', '彩票andiorid支付量');
transMap.put('riskMonitor-52006', '彩票PC支付量');
transMap.put('riskMonitor-53001', '点卡移动端订单量');
transMap.put('riskMonitor-53002', '点卡PC端订单量');
transMap.put('gms-150011', '融合发布商品');
transMap.put('riskMonitor-53003', '点卡移动端支付量');
transMap.put('gms-150012', '融合全量编辑 ');
transMap.put('riskMonitor-53004', '点卡PC端订支付量');
transMap.put('gms-150013', '融合高级编辑');
transMap.put('gms-150014', '融合查询商品');
transMap.put('riskMonitor-51007', '手机充值移动端成功量');
transMap.put('gms-150015', '融合批量查询商品');
transMap.put('riskMonitor-51008', '手机充值pc端成功量');
transMap.put('gms-150016', '融合更新商品状态');
transMap.put('riskMonitor-51009', '手机充值企销成功量');
transMap.put('gms-150017', '融合更新关联版式');
transMap.put('gms-150018', '融合设置SKU库存');
transMap.put('gms-150019', '融合新增SKU');
transMap.put('gms-150020', '融合更新SKU');
transMap.put('order-29', 'POP拍卖');
transMap.put('orderpipesubmitip--1', '订单区域');
transMap.put('order-31', '全球购');
transMap.put('order-32', '买卖宝');
transMap.put('promoRisk--1', '促销监控');
transMap.put('promoRisk-1', '单品促销');
transMap.put('promoRisk-4', '赠品促销');
transMap.put('promoRisk-6', '套装促销');
transMap.put('promoRisk-10', '总价促销');
transMap.put('promoRisk-8', '调价量');
transMap.put('promoRisk-11', '促销订单量');
transMap.put('promoRisk-9', '未来一小时');
transMap.put('order-189', '移动仓订单');
transMap.put('promoRisk-12', '正在进行');
transMap.put('order-37', '跨店铺满减');
transMap.put('order-38', '延保订单');
transMap.put('order-190', '易车订单');
transMap.put('order-194', '运营商虚拟业务');
transMap.put('order-39', '超限购促销优惠');
transMap.put('order-41', '优惠券4.0');
transMap.put('order-40', 'PC廊坊结算页SDK');
transMap.put('order-42', 'PC订单永丰');
transMap.put('order-43', 'PC订单黄村');
transMap.put('order-44', 'PC订单亦庄');
transMap.put('order-45', '手机廊坊结算页SDK');
transMap.put('order-191', '会员PLUS');
transMap.put('order-46', 'PC订单廊坊');
transMap.put('order-47', 'PC订单B28');
transMap.put('order-48', '微信廊坊结算页SDK');
transMap.put('order-49', '手Q廊坊结算页SDK');
transMap.put('stockbusi--1', '库存监控');
transMap.put('stockbusi-1000', '全部预占');
transMap.put('stockbusi-992', '廊坊移动');
transMap.put('stockbusi-993', '廊坊PC');
transMap.put('stockbusi-994', '廊坊微信手Q');
transMap.put('stockbusi-995', '廊坊秒杀');
transMap.put('stockbusi-996', '马桥移动');
transMap.put('stockbusi-997', '马桥PC');
transMap.put('stockbusi-998', '马桥微信手Q');
transMap.put('stockbusi-999', '马桥秒杀');
transMap.put('stockbusi-1007', '站点库存');
transMap.put('stockbusi-1010', '海尔协同仓');
transMap.put('stockbusi-1011', '非图书平行库存');
transMap.put('stockbusi-1012', '全部图书');
transMap.put('stockbusi-1013', '图书采销预售');
transMap.put('stockbusi-1014', '图书EDI预售');
transMap.put('stockbusi-1015', '图书J仓预售');
transMap.put('stockbusi-1016', '图书平行库存');
transMap.put('stockbusi-1017', '厂商直送');
transMap.put('stockbusi-1018', '全国发货');
transMap.put('stockbusi-1019', 'POPJIT');
transMap.put('stockbusi-1020', 'POP分区');
transMap.put('stockbusi-1021', 'POP本地购');
transMap.put('stockbusi-1022', '非FBP的POP');
transMap.put('stockbusi-1023', '订单提交(101)');
transMap.put('stockbusi-1024', '订单取消(102)');
transMap.put('stockbusi-1025', '修改配送中心(104)');
transMap.put('stockbusi-1026', '转移至生产(301)');
transMap.put('stockbusi-1027', '病单拉回(302)');
transMap.put('stockbusi-1028', '订单出库(405)');
transMap.put('stockbusi-1029', '现货入库(401)');
transMap.put('stockbusi-1030', '现货出库(402)');
transMap.put('stockbusi-1031', '配货出库(403)');
transMap.put('stockbusi-1032', '配货入库(404)');
transMap.put('stockbusi-1033', '配货计划(501)');
transMap.put('stockbusi-1034', '采购计划(601)');
transMap.put('stockbusi-1035', '锁定库存(201)');
transMap.put('stockbusi-1036', '不可售库存(4001)');
transMap.put('stockbusi-1037', '采购计划入(408)');
transMap.put('stockbusi-1038', '站点内配计划(正)');
transMap.put('stockbusi-1039', '站点内配计划(反)');
transMap.put('stockbusi-1040', '站点内配出库(正)');
transMap.put('stockbusi-1041', '站点内配出库(反)');
transMap.put('stockbusi-1042', '站点内配入库');
transMap.put('stockbusi-1043', '站点现货入库');
transMap.put('stockbusi-1044', '站点现货出库');
transMap.put('stockbusi-1045', '站点不可售库存');
transMap.put('orderpipeoverstock-1001', '管道一次拆分');
transMap.put('orderpipeoverstock-1002', '管道分支流程');
transMap.put('orderpipeoverstock-1003', '管道写中间件');
transMap.put('orderpipeoverstock-1004', '管道推OFW');
transMap.put('orderpipeoverstock-1005', '管道发MQ');
transMap.put('orderpipeoverstock-1006', '管道推台账');
transMap.put('orderpipeoverstock-1007', '管道写Peking');
transMap.put('promoRiskType--1', '促销sku监控');
transMap.put('promoRiskType-1', '单品促销');
transMap.put('promoRiskType-4', '赠品促销');
transMap.put('promoRiskType-6', '套装促销');
transMap.put('promoRiskType-10', '总价促销');
transMap.put('order-168', '拍卖保证金');
transMap.put('order-52', '节能补贴');
transMap.put('order-188', '总代订单');
transMap.put('order-57', '政企主站前台');
transMap.put('order-53', '商采订单');
transMap.put('order-54', 'VOP订单');
transMap.put('order-55', 'VSP订单');
transMap.put('order-56', '企销代下单');
transMap.put('order-58', 'POP新运费');
transMap.put('stockbusi-1001', 'B28机房');
transMap.put('stockbusi-1002', '亦庄机房');
transMap.put('stockbusi-1003', '黄村机房');
transMap.put('stockbusi-1004', '廊坊机房');
transMap.put('stockbusi-1005', '秒杀');
transMap.put('stockbusi-1006', '易迅');
transMap.put('stockbusi-1008', '中小件');
transMap.put('stockbusi-1009', '大件');
transMap.put('order-50', '跨店铺满免');
transMap.put('order-61', '预约订单');
transMap.put('order-59', '开普勒');
transMap.put('order-60', '开普勒全球购');
transMap.put('order-200', '福卡-购卡');
transMap.put('order-62', '福卡-提货');
transMap.put('order-63', '自营otc医药');
transMap.put('order-64', '抢购订单');
transMap.put('order-196', 'pop延保');
transMap.put('order-65', '拍卖m版');
transMap.put('order-66', '新促销引擎订单');
transMap.put('promoRiskType-20', '促销含有测试商品');
transMap.put('promoRiskType-21', '促销非采销岗创建');
transMap.put('promoRiskType-30', '调价比例过大');
transMap.put('promoRiskType-31', '测试商品调价');
transMap.put('promoRiskType-32', '非采销岗调价');
transMap.put('order-67', '白条支付');
transMap.put('order-68', '微信支付');
transMap.put('order-69', '京东支付');
transMap.put('order-70', 'M端订单');
transMap.put('order-71', '注册会员订单');
transMap.put('order-72', '铜牌会员订单');
transMap.put('order-73', '银牌会员订单');
transMap.put('order-74', '金牌会员订单');
transMap.put('order-75', '企业用户订单');
transMap.put('order-76', '钻石用户订单');
transMap.put('order-77', 'VIP用户订单');
transMap.put('order-78', '拍卖微信端');
transMap.put('order-79', 'PC订单亦庄移动');
transMap.put('order-80', 'PC订单永丰_2');
transMap.put('order-82', 'PC马驹桥结算页SDK');
transMap.put('order-83', '手机马驹桥结算页SDK');
transMap.put('order-84', '微信马驹桥结算页SDK');
transMap.put('order-85', '手Q马驹桥结算页SDK');
transMap.put('order-86', '马驹桥全部');
transMap.put('order-87', '通用下单马驹桥');
transMap.put('order-88', '全球购马驹桥');
transMap.put('order-89', '老版虚拟资产');
transMap.put('order-90', '新版虚拟资产');
transMap.put('order-91', '使用智能选券');
transMap.put('order-176', '京东云充值');
transMap.put('order-93', '手机北京结算页SDK');
transMap.put('order-94', '规则测试');
transMap.put('order-95', 'PC北京结算页SDK');
transMap.put('order-100000', '微信北京结算页SDK');
transMap.put('order-100001', '手Q北京结算页SDK');
transMap.put('order-100002', '秒杀北京结算页SDK');
transMap.put('order-100003', '秒杀廊坊结算页SDK');
transMap.put('order-100004', '秒杀马驹桥结算页SDK');
transMap.put('order-100009', 'JOS订单');
transMap.put('order-100005', 'JOS北京结算页SDK');
transMap.put('order-100006', 'JOS廊坊结算页SDK');
transMap.put('order-100007', 'JOS亦庄结算页SDK');
transMap.put('order-100008', 'JOS马驹桥结算页SDK');
transMap.put('login-28', '主站登录-永丰');
transMap.put('login-29', '主站登录-黄村');
transMap.put('login-30', '主站登录-廊坊');
transMap.put('login-31', '主站登录-亦庄');
transMap.put('login-32', '主站登录-香港葵涌');
transMap.put('promoRisk-13', '进行中单品');
transMap.put('promoRisk-14', '进行中赠品');
transMap.put('promoRisk-15', '进行中套装');
transMap.put('promoRisk-16', '进行中总价');
transMap.put('order-100010', '全球购税价分离');
transMap.put('order-200000', '压测1');
transMap.put('order-200001', '压测2');
transMap.put('order-200002', '压测3');
transMap.put('order-200003', '压测4');
transMap.put('order-200004', '压测5');
transMap.put('order-200005', '压测6');
transMap.put('order-200006', '压测7');
transMap.put('order-200007', '压测8');
transMap.put('order-200008', '压测9');
transMap.put('order-200009', '压测10');
transMap.put('order-200010', '自提订单');
transMap.put('order-200011', '自提混合订单');
transMap.put('order-200012', 'pop电子发票订单');
transMap.put('order-187', '流量充值');
transMap.put('order-199', '油卡充值');
transMap.put('order-198', '一元抢宝');
transMap.put('order-200013', '拍卖手Q端');
transMap.put('order-200014', 'popOTC订单');
transMap.put('order-200015', '一元抢宝');
transMap.put('order-200016', '一元抢宝pc');
transMap.put('order-200017', '一元抢宝m版');
transMap.put('order-200018', '一元抢宝app');
transMap.put('order-200019', '一元抢宝微信app');
transMap.put('order-200020', '一元抢宝手Qapp');
transMap.put('order-200021', '落地配订单');
transMap.put('order-200022', '手机小件京准达');
transMap.put('order-200023', 'PC小件京准达');
transMap.put('order-200024', '微信小件京准达');
transMap.put('order-200025', '手Q小件京准达');
transMap.put('order-200026', 'PC大件京准达');
transMap.put('order-200027', '手机大件京准达');
transMap.put('order-200028', '微信大件京准达');
transMap.put('order-200029', '手Q大件京准达');
transMap.put('order-200030', '山姆店订单');
transMap.put('order-200031', 'PC订单马驹桥');
transMap.put('order-200032', '京东入驻1号店订单');


String.prototype.replaceAll = function (reallyDo, replaceWith, ignoreCase) {
    if (!RegExp.prototype.isPrototypeOf(reallyDo)) {
        return this.replace(new RegExp(reallyDo, (ignoreCase ? "gi" : "g")), replaceWith);
    } else {
        return this.replace(reallyDo, replaceWith);
    }
};

/**拼装url*/
function getUrl(name, type, action, date, minute, count) {
    var url = '/' + action + '.action?queryVO.name=' + name + '&queryVO.rftype=' + type;
    if (date != undefined && date != null) {
        url += '&queryVO.searchDate=' + date;
    }
    if (minute != undefined && minute != null) {
        url += '&queryVO.minute=' + minute;
    }
    if (count != undefined && count != null) {
        url += '&queryVO.showCount=' + count;
    }
    return url;
}
var config = {};
$(function () {
    chrome.storage.local.get(function (itmes) {
        config.belowMiddle = itmes.risking.belowMiddle;
        config.compareYesterday = itmes.risking.compareYesterday;
        config.floatOverMiddle = itmes.risking.floatOverMiddle;
    });
    // $("#container").css("height", $(window).height() + "px");
    var param = GlobalUtils.GetRequest(location.search);
    var name = param.name || "order";
    var rftype = param.rftype || "99";
    var pageResult = {};
    $.ajax({
        url: "http://risking.jd.com/showCountNew.action?queryVO.showHtml=1&queryVO.init=1&queryVO.name=" + name + "&queryVO.rftype=" + rftype + "&" + 't=' + new Date().getTime(),
        type: "POST",
        async: false,
        beforeSend: function () {
        },
        error: function (XMLHttpRequest) {
        },
        success: function (data, textStatus) {
            pageResult = JSON.parse("{" + $($(data)[54]).html().match(/(.*\n)*\s*var\s*pageResult\s*=\s*\{(.*)\};(.*\n)*/)[2] + "}");
        },
        complete: function (XMLHttpRequest, textStatus) {
        }
    });
    yAxisTitle = pageResult.yAxisTitle;
    valueSuffix = pageResult.valueSuffix;
    options = createOptions('container');
    initTableNew(pageResult);
});
//
// function changeMonth(obj) {
//     var cYear = $('#currentYear').val();
//     if ($(obj).val() == cYear) {
//         var cMonth = $('#currentMonth').val();
//         $('#month').empty();
//         $('#month').append(optionHtml(cMonth));
//     } else {
//         $('#month').empty();
//         $('#month').append(optionHtml(12));
//     }
// }
// function changeWeek(obj) {
//     var weekOptions = $('#week_' + obj).html();
//     var h = weekOptions.replaceAll("tmpoption", "option");
//     $('#week').empty();
//     $('#week').append(h);
// }
// function optionHtml(month) {
//     var appendHtml = "";
//     for (var i = 1; i <= month; i++) {
//         appendHtml += "<option value=" + i + ">" + i + "</option>";
//     }
//     return appendHtml;
// }
// function setSelected(id, val) {
//     $("#" + id + " option[value=" + val + "]").attr("selected", "selected");
// }
// var cY = $('#currentYear').val();
// //初始化年份,月份, 周数
// setSelected("weekYear", cY);
// setSelected("monthYear", cY);
// setSelected('month', '10');
// changeWeek(cY);
// setSelected('week', '44');
